os: linux
dist: xenial
language: shell
sudo: required
services:
- docker
archlinux:
  packages:
  - wget
  - git
  script:
  - 'git clone https://github.com/jeksterslabds/jeksterslabShell.git'
  - 'export PATH="$PATH:jeksterslabShell/src"'
  - 'sudo pacman_install -f -d packages.csv'
script: 'curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash'
