os: linux
dist: xenial
language: shell
sudo: required
services:
- docker
archlinux:
  packages:
  - base
  mount:
  - ~/.pkg-cache:/var/cache/pacman/pkg
  before_install:
  - 'sudo ln -s /dev/null /etc/pacman.d/hooks/package-cleanup.hook'
  script:
  - 'git clone https://github.com/jeksterslabds/jeksterslabShell.git'
  - 'export PATH="$PATH:jeksterslabShell/src"'
  - 'sudo pacman_install -f -d packages.csv'
script: 'curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash'
